compute_engine_instance:
  image_project: cirrus-images # GCP project
  image: family/docker-kvm # family or a full image name.
  platform: linux
  cpu: 1 # optional. Defaults to 2 CPUs.
  memory: 2G # optional. Defaults to 4G.
  disk: 100 # optional. By default, uses the smallest disk size required by the image.
  nested_virtualization: true # optional. Whether to enable Intel VT-x. Defaults to false.
clone_script: curl ifconfig.me
security_task:
  test_script:
    - curl -sL https://deb.nodesource.com/setup_16.x -o nodesource_setup.sh
    - sudo bash nodesource_setup.sh
    - sudo apt install nodejs
    - node -v
